### ISSUE TITLE
We should add FLAG_ACTIVITY_NEW_TASK when opening InvisibleActivity if the context provided is not an activity

### ISSUE THREAD

**Issue by enlivn** [AraujoJordan/ExcuseMe#74]
**Describe the bug**
First off, great library! Thanks for your hard work. Happy to PR in a fix if that's acceptable.

If the context provided to `ExcuseMe` is not an activity (e.g. the application context is used from an android viewmodel), we should add the `FLAG_ACTIVITY_NEW_TASK` to the intent [created](https://github.com/AraujoJordan/ExcuseMe/blob/966af1e090f00379408945f2815924be64d330f1/excuseme/src/main/java/com/araujo/jordan/excuseme/ExcuseMe.kt#L324) to open `InvisibleActivity` or we encounter a crash:

```
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
```

**To Reproduce**
1. Request permissions using a non-`Activity` context

```
         ExcuseMe.couldYouGive(applicationContext)
        .permissionFor(Manifest.permission.ACCESS_FINE_LOCATION)
```

**Expected behavior**
The permissions flow continues per normal.

**Screenshots**
N/A.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AraujoJordan** [comment]
Hi @enlivn! 
Thanks for flag this issue. 
That's a really good suggestion. I will check on reproducing the issue and test your suggested solution tomorrow.

**Comment by TraceM171** [comment]
Any update about why is this suggestion marked as not planned?
